import { Raleway } from 'next/font/google';
import type { ReactNode } from 'react';

import { AppLayout } from '@/components/Layout';
import EmotionProvider from '@/components/Provider/emotion';

import '../styles/globals.css';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Next App Template',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <EmotionProvider>
          <AppLayout>{children}</AppLayout>
        </EmotionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
