import { Raleway } from 'next/font/google';
import type { ReactNode } from 'react';

import EmotionProvider from '@/components/Provider/emotion';

import '../styles/globals.css';

const inter = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Next App Template',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EmotionProvider>{children}</EmotionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
